---
version: "3.7"
services:
  nifi:
    image: apache/nifi:1.10.0
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - type: volume
        source: conf
        target: /opt/nifi/nifi-1.10.0/conf
      - type: volume
        source: content
        target: /opt/nifi/nifi-1.10.0/content_repository
      - type: volume
        source: db
        target: /opt/nifi/nifi-1.10.0/database_repository
      - type: volume
        source: flowfile
        target: /opt/nifi/nifi-1.10.0/flowfile_repository
      - type: volume
        source: provenance
        target: /opt/nifi/nifi-1.10.0/provenance_repository
      - type: volume
        source: logs
        target: /opt/nifi/nifi-1.10.0/logs
      - type: volume
        source: data
        target: /opt/nifi/nifi-1.10.0/data
volumes:
  conf:
  content:
  db:
  flowfile:
  provenance:
  logs:
  data:
...
