---
version: "3.3"
services:
  nifi:
    image: apache/nifi:1.3.0
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - type: bind
        source: ./conf
        target: /opt/nifi/nifi-1.3.0/conf
      - type: bind
        source: ./content_repository
        target: /opt/nifi/nifi-1.3.0/content_repository
      - type: bind
        source: ./database_repository
        target: /opt/nifi/nifi-1.3.0/database_repository
      - type: bind
        source: ./flowfile_repository
        target: /opt/nifi/nifi-1.3.0/flowfile_repository
      - type: bind
        source: ./provenance_repository
        target: /opt/nifi/nifi-1.3.0/provenance_repository
      - type: bind
        source: ./logs
        target: /opt/nifi/nifi-1.3.0/logs
      - type: bind
        source: ./data
        target: /opt/nifi/nifi-1.3.0/data
...